### ISSUE TITLE
post_evaluationsのkindデータ型

### ISSUE THREAD

**Issue by honbin** [toqoz/UITalk#18]
これintegerだよね？一応念のため確認

**Comment by toqoz** [comment]
stringです。integerだと文字列渡された時、to_i呼ばれて0になってvaludation通っちゃうのが嫌だなーと. それとも1から始まるintegerでもいいかなと、今思いました

**Comment by toqoz** [comment]
あ、そもそも1~にしてますね... どっちでも良いんですが, もしやkind増えたらstringのが良いかなーとか. でもそんな増えなさそうですし, integerで良い気がしてきました.

**Comment by honbin** [comment]
なるほどね、、ま、データ自体1,2以上増えることなさそうだし、、integerにしようかね
